services:
  postgres:
    image: postgres:16-alpine
    container_name: incidents-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5050:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["-c", "listen_addresses=*"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - incidents-network

  incidents:
    image: julianamlb/incidentes:latest
    container_name: incidentes-servicio
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      VEHICLES_API_URL: ${VEHICLES_API_URL}
      SNS_TOPIC_ARN: ${SNS_TOPIC_ARN}
      AWS_REGION: ${AWS_REGION}
      LOG_LEVEL: INFO
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public.pem
    ports:
      - "8080:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./secrets/jwt_public.pem:/run/secrets/jwt_public.pem:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - incidents-network
    # ← CAMBIO: usar Gunicorn en lugar de runserver
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 incidents.wsgi:application

volumes:
  postgres_data:

networks:
  incidents-network:
    driver: bridge