[mypy]
plugins = mypy_django_plugin.main
exclude = (^|.*/)(venv|\.venv|migrations)/

[mypy.plugins.django-stubs]
django_settings_module = incidents.settings.test

[mypy-pybreaker.*]
ignore_missing_imports = True