sonar.organization=fleetops-corp
sonar.projectKey=FleetOps-Corp_FleetOps-Incidents-Service
sonar.projectName=FleetOps-Incidents-Service

# Carpetas analizadas y excluidas
sonar.sources=incidents
sonar.tests=tests
sonar.exclusions=**/migrations/**,**/tests/**, incidents/settings/*, incidents/infrastructure/config/*

# Ruta al reporte de cobertura de Pytest que genera tu pipeline
sonar.python.coverage.reportPaths=coverage.xml

sonar.scm.disabled=false
sonar.path.reducer.enabled=true