# Generated by Django 4.2.13 on 2026-07-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("fecha_hora", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id_conductor", models.CharField(max_length=255)),
                ("placa_vehiculo", models.CharField(max_length=20)),
                (
                    "tipo_incidente",
                    models.CharField(
                        choices=[
                            ("HUMANO", "Human Incident"),
                            ("MECANICO", "Mechanical Incident"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gravedad",
                    models.CharField(
                        choices=[("LEVE", "Mild"), ("GRAVE", "Severe")], max_length=20
                    ),
                ),
                ("descripcion", models.TextField()),
            ],
            options={
                "db_table": "incidents",
                "indexes": [
                    models.Index(
                        fields=["placa_vehiculo"], name="incidents_placa_v_566a5f_idx"
                    ),
                    models.Index(
                        fields=["id_conductor"], name="incidents_id_cond_b6d361_idx"
                    ),
                    models.Index(
                        fields=["tipo_incidente"], name="incidents_tipo_in_2b1f18_idx"
                    ),
                    models.Index(
                        fields=["gravedad"], name="incidents_graveda_6fdb57_idx"
                    ),
                    models.Index(
                        fields=["fecha_hora"], name="incidents_fecha_h_36362c_idx"
                    ),
                ],
            },
        ),
    ]
